default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: <%= ENV.fetch('PG_HOST',  'db') %>
  port: 5432

development:
  <<: *default
  database: todo

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
